### ISSUE TITLE
Handle Case Sensitive Keywords

### ISSUE THREAD

**Issue by iSumitBanik** [Olanetsoft/web3terms#13]
**ISSUE**

Currently, the keyword that is present inside the `terms.json` is matched exactly with the provided input KW from the tweet which shouldn't be matched exactly. So, it's better to handle the case of the keyword.

**SOLUTION**

Converting the input KW to lowercase and comparing the KW (in lower case) present in `terms.json` should solve the issue.

**Comment by Olanetsoft** [comment]
Looking to resolve this @iSumitBanik ASAP
