### ISSUE TITLE
Feat: Add More Web3 Terminologies

### ISSUE THREAD

**Issue by Olanetsoft** [Olanetsoft/web3terms#32]
- Add more web3 terms [here](https://github.com/Olanetsoft/web3terms/blob/develop/data/terms.json)
- Follow the format in the file
-  The meaning length must not exceed 280 characters.

**Comment by anant-strong** [comment]
hey Olanetsoft, can I just PR after adding web3 terms in the json you mentioned.

**Comment by anant-strong** [comment]
hey Olanetsoft, I have proposed PR https://github.com/Olanetsoft/web3terms/pull/56 for this issue. Please, have a look if that is acceptable or not.

**Comment by Rabeet8** [comment]
hey Olanetsoft, I have proposed a PR after adding a web3 term.

Kindly have look at it.

Thanks.

**Comment by firascodes** [comment]
hey Olanetsoft, Created a PR after another addition to the web3 terms list.
Kindly check it out!

**Comment by johnwinifred** [comment]
Can I work on this too
