### ISSUE TITLE
Fix: Fix all the terms without tag

### ISSUE THREAD

**Issue by Olanetsoft** [Olanetsoft/web3terms#33]
Fix all the Web3 terms in the terms.json without a tag. e.g. we have some in this format `is a ....` or ` This is a`, change it to contain the terms like `Bitcoin is a ...`

**Comment by ahmedsilat44** [comment]
Hey @Olanetsoft I would like to take on this task. Could you assign it to me. Thanks 😄

**Comment by Olanetsoft** [comment]
Done. Send Pr when it's ready... @ahmedsilat44

**Comment by ahmedsilat44** [comment]
Hey, I have a question. Is this project also a part of hacktoberfest ? cause there is no hacktoberfest label on the issue. I am new to OSS and hacktoberfest so its a little confusing.

**Comment by Olanetsoft** [comment]
> Hey, I have a question. Is this project also a part of hacktoberfest ? cause there is no hacktoberfest label on the issue. I am new to OSS and hacktoberfest so its a little confusing.

Yes, the project itself has the hacktoberfest label.
