### ISSUE TITLE
Fix: Format ReadMe

### ISSUE THREAD

**Issue by Olanetsoft** [Olanetsoft/web3terms#34]
- Add required information where necessary
- Add styles or formats to make the ReadMe better

**Comment by Rishav-12** [comment]
@Olanetsoft  Can I work on this please?

**Comment by Olanetsoft** [comment]
Sure @Rishav-12

**Comment by Rishav-12** [comment]
On it 😃

**Comment by Rishav-12** [comment]
Quick question:

Should I merge the Contributing and the After making a change sections of the README? 🤔

**Comment by choubari** [comment]
Hello @Olanetsoft , if the issue is still available, I would like to format the contributing.md

**Comment by Rishav-12** [comment]
I think this Issue can be closed now?
