### ISSUE TITLE
Fix: Update/Summarise web3 term meaning not more than 280 character including space.

### ISSUE THREAD

**Issue by Olanetsoft** [Olanetsoft/web3terms#41]
This update is significant because Twitter API won't respond if the meaning length exceeds 280 characters.

**Comment by oneknucklehead** [comment]
Can i work on this?

**Comment by Olanetsoft** [comment]
Sure @oneknucklehead

**Comment by AdnanIkram** [comment]
hi,
can i work on this, and could you guide me how to fix it. 
This will be my first open source contribution. Any guidance, what ever it will be, is useful. 

Thanks

**Comment by Olanetsoft** [comment]
> hi, can i work on this, and could you guide me how to fix it. This will be my first open source contribution. Any guidance, what ever it will be, is useful.
> 
> Thanks

Thanks for your input and also trying to contribute.

Someone already worked on this.
