### ISSUE TITLE
Fix: Update all `terms` to lower case

### ISSUE THREAD

**Issue by Olanetsoft** [Olanetsoft/web3terms#47]
#52

**Comment by jebitok-dev** [comment]
Hi, I would be interested in contributing to this. Would also need clarification I'm seeing terms.json is in lowercase should it be capitalised or which file with terms are you referring to ✊🚀

**Comment by Olanetsoft** [comment]
> Hi, I would be interested in contributing to this. Would also need clarification I'm seeing terms.json is in lowercase should it be capitalised or which file with terms are you referring to ✊🚀

Thank you @jebitok-dev 

The issue was to fix the content inside the terms.json, not the name itself. Someone already sent a PR. 🥲
