### ISSUE TITLE
feat: Add tests to verify web3 terms data format 

### ISSUE THREAD

**Issue by xeno097** [Olanetsoft/web3terms#62]
### Context

Issue [35](https://github.com/Olanetsoft/web3terms/issues/35) specifies that the term's `meaning` should be 280 characters long or less and the `term` should be lowercase but currently, nothing enforces this rule or warns about it, which means that the only way to notice this is either during a code review or if the Twitter API does not respond as explained here [41](https://github.com/Olanetsoft/web3terms/issues/41)

### Suggested Solution
- Add tests to check that every `meaning` is 280 characters or less and the `term` is lower case
- Add a GitHub action that runs the tests when a pull request is opened to check if the data complies with the before-mentioned constraints

### Extra
- A test to verify that every `term` is unique could be added

**Comment by Olanetsoft** [comment]
> ### Context
> Issue [35](https://github.com/Olanetsoft/web3terms/issues/35) specifies that the term's `meaning` should be 280 characters long or less and the `term` should be lowercase but currently, nothing enforces this rule or warns about it, which means that the only way to notice this is either during a code review or if the Twitter API does not respond as explained here [41](https://github.com/Olanetsoft/web3terms/issues/41)
> 
> ### Suggested Solution
> * Add tests to check that every `meaning` is 280 characters or less and the `term` is lower case
> * Add a GitHub action that runs the tests when a pull request is opened to check if the data complies with the before-mentioned constraints
> 
> ### Extra
> * A test to verify that every `term` is unique could be added

Are you going to work on the github action?

**Comment by xeno097** [comment]
> > ### Context
> > Issue [35](https://github.com/Olanetsoft/web3terms/issues/35) specifies that the term's `meaning` should be 280 characters long or less and the `term` should be lowercase but currently, nothing enforces this rule or warns about it, which means that the only way to notice this is either during a code review or if the Twitter API does not respond as explained here [41](https://github.com/Olanetsoft/web3terms/issues/41)
> > ### Suggested Solution
> > 
> > * Add tests to check that every `meaning` is 280 characters or less and the `term` is lower case
> > * Add a GitHub action that runs the tests when a pull request is opened to check if the data complies with the before-mentioned constraints
> > 
> > ### Extra
> > 
> > * A test to verify that every `term` is unique could be added
> 
> Are you going to work on the github action?

 Sure, I'll try to have it ready for tomorrow
