### ISSUE TITLE
Feat: Add Husky and define git hooks to sort and test automatically when a commit is made

### ISSUE THREAD

**Issue by choubari** [Olanetsoft/web3terms#84]
I saw in the Readme that after making a change we need to :

1. Sort the file: `yarn run sort`
2. Run a test to check all definition length: `yarn test`

Instead of manually doing that by each contributor, we can install Husky and define a pre commit hook to run these whenever we want to commit our changes.

I would like to work on this issue if possible.

**Comment by Olanetsoft** [comment]
@choubari Kindly proceed to work on this, please.

**Comment by choubari** [comment]
working on it

**Comment by Olanetsoft** [comment]
> working on it

okay

**Comment by choubari** [comment]
I found that Husky is already installed and the test command is already set up . So I added the sort command to the Huskt precommit hook in the PR #107
