### ISSUE TITLE
Docs: Add a short explanation of conventional commits in the contributing.md file

### ISSUE THREAD

**Issue by choubari** [Olanetsoft/web3terms#85]
I saw in the commit history that you're following the conventional commits, which may not be familiar to new contributors.

I would like to add a short explanation with practical examples in the contributing.md file to help new contributors write a better subject line in their commits before contributing.

I can work on this issue.

**Comment by Olanetsoft** [comment]
@choubari proceed, please

**Comment by choubari** [comment]
working on it

**Comment by Olanetsoft** [comment]
> working on it

Okay, any update?

**Comment by choubari** [comment]
Opened PR #106
